### PR TITLE
Feature: add spark sink hbase plugin

### PR DESCRIPTION
**Pull request by godliness**
Depends on `hbase-connectors`, we could load(bulk load) data into hbase by spark.

For fixing version conflicts, i changed `org.apache.phoenix.phoenix-spark` dependency version of `plugin-spark-phoenix-core`  to `5.0.0-HBase-2.0 `

PTAL

@garyelephant @RickyHuo

### CODE REVIEW

**Comment by godliness** [comment]
**Config example:**

```
 hbase {
    source_table_name = "hive_dataset"
    hbase.zookeeper.quorum = "centos01:2181,centos02:2181,centos03:2181"
    catalog = "{\"table\":{\"namespace\":\"default\", \"name\":\"customer\"},\"rowkey\":\"c_custkey\",\"columns\":{\"c_custkey\":{\"cf\":\"rowkey\", \"col\":\"c_custkey\", \"type\":\"bigint\"},\"c_name\":{\"cf\":\"info\", \"col\":\"c_name\", \"type\":\"string\"},\"c_address\":{\"cf\":\"info\", \"col\":\"c_address\", \"type\":\"string\"},\"c_city\":{\"cf\":\"info\", \"col\":\"c_city\", \"type\":\"string\"},\"c_nation\":{\"cf\":\"info\", \"col\":\"c_nation\", \"type\":\"string\"},\"c_region\":{\"cf\":\"info\", \"col\":\"c_region\", \"type\":\"string\"},\"c_phone\":{\"cf\":\"info\", \"col\":\"c_phone\", \"type\":\"string\"},\"c_mktsegment\":{\"cf\":\"info\", \"col\":\"c_mktsegment\", \"type\":\"string\"}}}"
    staging_dir = "/tmp/hbase-staging/2020.11.9/"
    save_mode = "overwrite"
}
```

**Comment by RickyHuo** [comment]
@godliness Good Job.

请在 https://github.com/InterestingLab/waterdrop-docs 项目中提交PR补充对应插件文档

**Comment by godliness** [comment]
@RickyHuo  文档PR已提交 https://github.com/InterestingLab/waterdrop-docs/pull/24

**Comment by garyelephant** [comment]
Good job, thanks @godliness

**Review by garyelephant — APPROVED** [review]

**Pull request merged**
